/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_cat_ai_platform_jni_c_jni */

#ifndef _Included_io_cat_ai_platform_jni_c_jni
#define _Included_io_cat_ai_platform_jni_c_jni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    integer_pointer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_integer_1pointer
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    boolean_pointer
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_boolean_1pointer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    byte_pointer
 * Signature: (B)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_byte_1pointer
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    char_pointer
 * Signature: (C)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_char_1pointer
  (JNIEnv *, jobject, jchar);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    short_pointer
 * Signature: (S)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_short_1pointer
  (JNIEnv *, jobject, jshort);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    float_pointer
 * Signature: (F)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_float_1pointer
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    long_pointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_long_1pointer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    double_pointer
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_double_1pointer
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    string_pointer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_string_1pointer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    assign_byte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_assign_1byte
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    assign_boolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_assign_1boolean
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    assign_char
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_assign_1char
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    assign_short
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_assign_1short
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    assign_integer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_assign_1integer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    assign_float
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_assign_1float
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    assign_long
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_assign_1long
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    assign_double
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_assign_1double
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_boolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1boolean
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_byte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1byte
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_short
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1short
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_char
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1char
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_int
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1int
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_float
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1float
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_long
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1long
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_double
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1double
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    deref_string
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_cat_ai_platform_jni_c_1jni_deref_1string
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_malloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    calloc
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_calloc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    realloc
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_realloc
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_platform_jni_c_1jni_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    boolean_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_boolean_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    char_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_char_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    short_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_short_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    int_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_int_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    byte_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_byte_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    long_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_long_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    float_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_float_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    double_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_double_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    string_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_string_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    mem_cpy
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_mem_1cpy
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    mem_move
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_mem_1move
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    mem_chr
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_mem_1chr
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    mem_cmp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_mem_1cmp
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    mem_set
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_mem_1set
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_cat
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1cat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    strn_cat
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_strn_1cat
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_chr
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1chr
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    strr_chr
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_strr_1chr
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_cmp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1cmp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    strn_cmp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_strn_1cmp
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_coll
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1coll
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_cpy
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1cpy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_len
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1len
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_spn
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1spn
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_cspn
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1cspn
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_pbrk
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1pbrk
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_str
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1str
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_tok
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1tok
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_platform_jni_c_jni
 * Method:    str_xfrm
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_platform_jni_c_1jni_str_1xfrm
  (JNIEnv *, jobject, jlong, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
