/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_cat_ai_snmm_core_jni_SnmmCoreJni */

#ifndef _Included_io_cat_ai_snmm_core_jni_SnmmCoreJni
#define _Included_io_cat_ai_snmm_core_jni_SnmmCoreJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    integer_pointer
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_integer_1pointer
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    boolean_pointer
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_boolean_1pointer
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    byte_pointer
 * Signature: (B)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_byte_1pointer
  (JNIEnv *, jobject, jbyte);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    char_pointer
 * Signature: (C)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_char_1pointer
  (JNIEnv *, jobject, jchar);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    short_pointer
 * Signature: (S)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_short_1pointer
  (JNIEnv *, jobject, jshort);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    float_pointer
 * Signature: (F)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_float_1pointer
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    long_pointer
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_long_1pointer
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    double_pointer
 * Signature: (D)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_double_1pointer
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    string_pointer
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_string_1pointer
  (JNIEnv *, jobject, jstring);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    assign_byte
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_assign_1byte
  (JNIEnv *, jobject, jlong, jbyte);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    assign_boolean
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_assign_1boolean
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    assign_char
 * Signature: (JC)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_assign_1char
  (JNIEnv *, jobject, jlong, jchar);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    assign_short
 * Signature: (JS)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_assign_1short
  (JNIEnv *, jobject, jlong, jshort);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    assign_integer
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_assign_1integer
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    assign_float
 * Signature: (JF)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_assign_1float
  (JNIEnv *, jobject, jlong, jfloat);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    assign_long
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_assign_1long
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    assign_double
 * Signature: (JD)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_assign_1double
  (JNIEnv *, jobject, jlong, jdouble);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_boolean
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1boolean
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_byte
 * Signature: (J)B
 */
JNIEXPORT jbyte JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1byte
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_short
 * Signature: (J)S
 */
JNIEXPORT jshort JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1short
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_char
 * Signature: (J)C
 */
JNIEXPORT jchar JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1char
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_int
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1int
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_float
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1float
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_long
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1long
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_double
 * Signature: (J)D
 */
JNIEXPORT jdouble JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1double
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    deref_string
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_deref_1string
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    boolean_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_boolean_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    char_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_char_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    short_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_short_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    int_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_int_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    byte_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_byte_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    long_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_long_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    float_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_float_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    double_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_double_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    string_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_string_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    byte_pointer_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_byte_1pointer_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    char_pointer_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_char_1pointer_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    short_pointer_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_short_1pointer_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    integer_pointer_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_integer_1pointer_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    float_pointer_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_float_1pointer_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    long_pointer_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_long_1pointer_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    double_pointer_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_double_1pointer_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    string_pointer_size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_string_1pointer_1size
  (JNIEnv *, jobject);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    malloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_malloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    malloc_struct
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_malloc_1struct
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    calloc
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_calloc
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    realloc
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_realloc
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    mem_cpy
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_mem_1cpy
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    mem_move
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_mem_1move
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    mem_chr
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_mem_1chr
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    mem_cmp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_mem_1cmp
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    mem_set
 * Signature: (JII)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_mem_1set
  (JNIEnv *, jobject, jlong, jint, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_cat
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1cat
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    strn_cat
 * Signature: (JJI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_strn_1cat
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_chr
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1chr
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    strr_chr
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_strr_1chr
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_cmp
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1cmp
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    strn_cmp
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_strn_1cmp
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_coll
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1coll
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_cpy
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1cpy
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_len
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1len
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_spn
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1spn
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_cspn
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1cspn
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_pbrk
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1pbrk
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_str
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1str
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_tok
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1tok
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    str_xfrm
 * Signature: (JJI)I
 */
JNIEXPORT jint JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_str_1xfrm
  (JNIEnv *, jobject, jlong, jlong, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_alloc
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1alloc
  (JNIEnv *, jobject, jint);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1free
  (JNIEnv *, jobject, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_byte_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1byte_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_char_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1char_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_short_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1short_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_int_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1int_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_float_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1float_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_long_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1long_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_double_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1double_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_string_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1string_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_pointer_key
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1pointer_1key
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_boolean_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1boolean_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_byte_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1byte_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_char_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1char_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_short_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1short_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_int_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1int_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_long_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1long_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_float_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1float_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_double_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1double_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_get_string_member
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1get_1string_1member
  (JNIEnv *, jobject, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_boolean_member
 * Signature: (ZIJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1boolean_1member
  (JNIEnv *, jobject, jboolean, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_byte_member
 * Signature: (BIJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1byte_1member
  (JNIEnv *, jobject, jbyte, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_and_get_int_member
 * Signature: (IIJ)J
 */
JNIEXPORT jlong JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1and_1get_1int_1member
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_char_member
 * Signature: (CIJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1char_1member
  (JNIEnv *, jobject, jchar, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_short_member
 * Signature: (SIJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1short_1member
  (JNIEnv *, jobject, jshort, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_int_member
 * Signature: (IIJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1int_1member
  (JNIEnv *, jobject, jint, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_long_member
 * Signature: (JIJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1long_1member
  (JNIEnv *, jobject, jlong, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_float_member
 * Signature: (FIJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1float_1member
  (JNIEnv *, jobject, jfloat, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_double_member
 * Signature: (DIJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1double_1member
  (JNIEnv *, jobject, jdouble, jint, jlong);

/*
 * Class:     io_cat_ai_snmm_core_jni_SnmmCoreJni
 * Method:    struct_put_string_member
 * Signature: (Ljava/lang/String;IJ)V
 */
JNIEXPORT void JNICALL Java_io_cat_ai_snmm_core_jni_SnmmCoreJni_struct_1put_1string_1member
  (JNIEnv *, jobject, jstring, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
